.PHONY: clean All

All:
	@echo "----------Building project:[ staticMember - Debug ]----------"
	@cd "staticMember" && "$(MAKE)" -f  "staticMember.mk"
clean:
	@echo "----------Cleaning project:[ staticMember - Debug ]----------"
	@cd "staticMember" && "$(MAKE)" -f  "staticMember.mk" clean
