.PHONY: clean All

All:
	@echo "----------Building project:[ Movie - Debug ]----------"
	@cd "Movie" && "$(MAKE)" -f  "Movie.mk"
clean:
	@echo "----------Cleaning project:[ Movie - Debug ]----------"
	@cd "Movie" && "$(MAKE)" -f  "Movie.mk" clean
