.PHONY: clean All

All:
	@echo "----------Building project:[ ShallowCopying - Debug ]----------"
	@cd "ShallowCopying" && "$(MAKE)" -f  "ShallowCopying.mk"
clean:
	@echo "----------Cleaning project:[ ShallowCopying - Debug ]----------"
	@cd "ShallowCopying" && "$(MAKE)" -f  "ShallowCopying.mk" clean
