.PHONY: clean All

All:
	@echo "----------Building project:[ Constant - Debug ]----------"
	@cd "Constant" && "$(MAKE)" -f  "Constant.mk"
clean:
	@echo "----------Cleaning project:[ Constant - Debug ]----------"
	@cd "Constant" && "$(MAKE)" -f  "Constant.mk" clean
