.PHONY: clean All

All:
	@echo "----------Building project:[ centChange - Debug ]----------"
	@cd "centChange" && "$(MAKE)" -f  "centChange.mk"
clean:
	@echo "----------Cleaning project:[ centChange - Debug ]----------"
	@cd "centChange" && "$(MAKE)" -f  "centChange.mk" clean
