.PHONY: clean All

All:
	@echo "----------Building project:[ IncrementNDecrement - Debug ]----------"
	@cd "IncrementNDecrement" && "$(MAKE)" -f  "IncrementNDecrement.mk"
clean:
	@echo "----------Cleaning project:[ IncrementNDecrement - Debug ]----------"
	@cd "IncrementNDecrement" && "$(MAKE)" -f  "IncrementNDecrement.mk" clean
