.PHONY: clean All

All:
	@echo "----------Building project:[ PointerArrayMul - Debug ]----------"
	@cd "PointerArrayMul" && "$(MAKE)" -f  "PointerArrayMul.mk"
clean:
	@echo "----------Cleaning project:[ PointerArrayMul - Debug ]----------"
	@cd "PointerArrayMul" && "$(MAKE)" -f  "PointerArrayMul.mk" clean
