.PHONY: clean All

All:
	@echo "----------Building project:[ pointerDereferencing - Debug ]----------"
	@cd "pointerDereferencing" && "$(MAKE)" -f  "pointerDereferencing.mk"
clean:
	@echo "----------Cleaning project:[ pointerDereferencing - Debug ]----------"
	@cd "pointerDereferencing" && "$(MAKE)" -f  "pointerDereferencing.mk" clean
