.PHONY: clean All

All:
	@echo "----------Building project:[ PointersDeclaration - Debug ]----------"
	@cd "PointersDeclaration" && "$(MAKE)" -f  "PointersDeclaration.mk"
clean:
	@echo "----------Cleaning project:[ PointersDeclaration - Debug ]----------"
	@cd "PointersDeclaration" && "$(MAKE)" -f  "PointersDeclaration.mk" clean
