.PHONY: clean All

All:
	@echo "----------Building project:[ VectorExercise - Debug ]----------"
	@cd "VectorExercise" && "$(MAKE)" -f  "VectorExercise.mk"
clean:
	@echo "----------Cleaning project:[ VectorExercise - Debug ]----------"
	@cd "VectorExercise" && "$(MAKE)" -f  "VectorExercise.mk" clean
