.PHONY: clean All

All:
	@echo "----------Building project:[ SalesData - Debug ]----------"
	@cd "SalesData" && "$(MAKE)" -f  "SalesData.mk"
clean:
	@echo "----------Cleaning project:[ SalesData - Debug ]----------"
	@cd "SalesData" && "$(MAKE)" -f  "SalesData.mk" clean
