.PHONY: clean All

All:
	@echo "----------Building project:[ Person - Debug ]----------"
	@cd "Person" && "$(MAKE)" -f  "Person.mk"
clean:
	@echo "----------Cleaning project:[ Person - Debug ]----------"
	@cd "Person" && "$(MAKE)" -f  "Person.mk" clean
