.PHONY: clean All

All:
	@echo "----------Building project:[ ScreenAndWindow - Debug ]----------"
	@cd "ScreenAndWindow" && "$(MAKE)" -f  "ScreenAndWindow.mk"
clean:
	@echo "----------Cleaning project:[ ScreenAndWindow - Debug ]----------"
	@cd "ScreenAndWindow" && "$(MAKE)" -f  "ScreenAndWindow.mk" clean
