.PHONY: clean All

All:
	@echo "----------Building project:[ ListTest - Debug ]----------"
	@cd "ListTest" && "$(MAKE)" -f  "ListTest.mk"
clean:
	@echo "----------Cleaning project:[ ListTest - Debug ]----------"
	@cd "ListTest" && "$(MAKE)" -f  "ListTest.mk" clean
