.PHONY: clean All

All:
	@echo "----------Building project:[ ArrayParameters - Debug ]----------"
	@cd "ArrayParameters" && "$(MAKE)" -f  "ArrayParameters.mk"
clean:
	@echo "----------Cleaning project:[ ArrayParameters - Debug ]----------"
	@cd "ArrayParameters" && "$(MAKE)" -f  "ArrayParameters.mk" clean
