.PHONY: clean All

All:
	@echo "----------Building project:[ Functions - Debug ]----------"
	@cd "FunctionPrototypes" && "$(MAKE)" -f  "Functions.mk"
clean:
	@echo "----------Cleaning project:[ Functions - Debug ]----------"
	@cd "FunctionPrototypes" && "$(MAKE)" -f  "Functions.mk" clean
