.PHONY: clean All

All:
	@echo "----------Building project:[ RewriteTestList - Debug ]----------"
	@cd "RewriteTestList" && "$(MAKE)" -f  "RewriteTestList.mk"
clean:
	@echo "----------Cleaning project:[ RewriteTestList - Debug ]----------"
	@cd "RewriteTestList" && "$(MAKE)" -f  "RewriteTestList.mk" clean
