.PHONY: clean All

All:
	@echo "----------Building project:[ TestOne - Debug ]----------"
	@cd "TestOne" && "$(MAKE)" -f  "TestOne.mk"
clean:
	@echo "----------Cleaning project:[ TestOne - Debug ]----------"
	@cd "TestOne" && "$(MAKE)" -f  "TestOne.mk" clean
