.PHONY: clean All

All:
	@echo "----------Building project:[ MyString - Debug ]----------"
	@cd "MyString" && "$(MAKE)" -f  "MyString.mk"
clean:
	@echo "----------Cleaning project:[ MyString - Debug ]----------"
	@cd "MyString" && "$(MAKE)" -f  "MyString.mk" clean
