.PHONY: clean All

All:
	@echo "----------Building project:[ MystringMemberFunction - Debug ]----------"
	@cd "MystringMemberFunction" && "$(MAKE)" -f  "MystringMemberFunction.mk"
clean:
	@echo "----------Cleaning project:[ MystringMemberFunction - Debug ]----------"
	@cd "MystringMemberFunction" && "$(MAKE)" -f  "MystringMemberFunction.mk" clean
