.PHONY: clean All

All:
	@echo "----------Building project:[ MystringMemberfunctions - Debug ]----------"
	@cd "MystringMemberfunctions" && "$(MAKE)" -f  "MystringMemberfunctions.mk"
clean:
	@echo "----------Cleaning project:[ MystringMemberfunctions - Debug ]----------"
	@cd "MystringMemberfunctions" && "$(MAKE)" -f  "MystringMemberfunctions.mk" clean
